### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by duxbuse** [kamilchodola/wait-for-workflow-action#10]
Hey mate when I'm trying to use this action I get:
```text
line 1: /runner/_work/_actions/kamilchodola/wait-for-workflow-action/1.1.0/scripts/wait-for-workflow.sh: Permission denied
```

**Comment by kamilchodola** [comment]
Hi!

I think I made small issue in there in regards of script permission - let me take a look

**Comment by 2opremio** [comment]
I am getting the same problem

**Comment by budgetdevv** [comment]
Same

**Comment by LegendRoland-K** [comment]
same

**Comment by willquill** [comment]
Same issue on 2025-09-22 on version 1.1.0 when declared like this:

```
      - name: Wait for Security Workflow
        uses: kamilchodola/wait-for-workflow-action@1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: "security.yml"
          max_wait_minutes: "3"
          interval: "5"
          timeout: "60"
          org_name: ${{ github.repository_owner }}
          repo_name: ${{ github.repository }}
```
